$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },

        860:{
            items:5
        },
        1400:{
            items:7
        }
    }
})